name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Set default working directory for run steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          # pytest, flake8, black, pytest-cov are already in requirements.txt

      - name: Lint with Flake8
        run: flake8 . # Run flake8 from backend/ directory
        # Alternatively, from repo root: flake8 backend/

      - name: Check formatting with Black
        run: black --check . # Run black from backend/ directory
        # Alternatively, from repo root: black --check backend/

      - name: Run tests with Pytest
        run: pytest tests/ # Run pytest from backend/ directory, targeting tests/ subdir
        # Alternatively, from repo root: pytest backend/tests/
        # FLASK_CONFIG=testing is set by backend/pytest.ini
        # PYTHONPATH might need to be set if running from repo root and imports fail.
        # env:
        #   PYTHONPATH: . # if running pytest from repo root for backend package

      - name: Build Docker image
        # This step needs to run from the repository root where ./backend is a subdirectory
        # So, override the default working-directory for this step.
        working-directory: .
        run: docker build -t kanban-backend-test:${{ github.sha }} -f backend/Dockerfile ./backend
